---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ansible
name: windows_compliance
version: 1.0.0
readme: README.md
authors:
  - Red Hat Ansible Content Team
description: |
  Enterprise-grade Ansible collection for Windows security compliance automation.
  Modernized implementation using native ansible.windows modules with structured
  JSON audit data and consolidated task management. Provides comprehensive
  automation for DISA STIG and CIS benchmark configurations on Windows servers
  with enterprise-grade reliability and performance optimization.
license_file: LICENSE
tags:
  - windows
  - security
  - compliance
  - stig
  - cis
  - hardening
  - audit
  - enterprise
  - automation
  - modernized
repository: https://github.com/ansible-collections/ansible.windows_compliance
documentation: https://docs.ansible.com/ansible/devel/collections/ansible/windows_compliance
homepage: https://github.com/ansible-collections/ansible.windows_compliance
issues: https://github.com/ansible-collections/ansible.windows_compliance/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
